// components/landing/how-it-works-section.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { Check } from "lucide-react";

const steps = [
  {
    number: "I",
    title: "Connect your business systems",
    description:
      "Import your brand playbook, product manuals, and historical conversation data. Supports API, CSV, and direct database connections. A dedicated customer success manager guides you through setup — live in 30 minutes.",
    visual: {
      type: "checklist",
      title: "Setup Checklist",
      items: [
        { label: "Brand voice & tone guide", done: true },
        { label: "Product manual / FAQ", done: true },
        { label: "Historical conversation data", done: true },
        { label: "Channel integration (LINE / WhatsApp)", done: true },
        { label: "Knowledge base language config", done: false, active: true },
        { label: "Pre-launch QA & sign-off", done: false },
      ],
      footer: "Estimated setup time: 30 minutes",
    },
  },
  {
    number: "II",
    title: "Configure your multilingual knowledge base",
    description:
      "Upload your primary knowledge base in any language. The system automatically translates and syncs to all 11 language versions. Each language is independently validated to ensure terminology, brand tone, and formatting stay consistent.",
    visual: {
      type: "languages",
      title: "Knowledge Base Sync Status",
      items: [
        {
          lang: "Chinese (Primary)",
          code: "ZH",
          status: "Primary",
          done: true,
        },
        { lang: "Thai", code: "TH", status: "Synced", done: true },
        { lang: "Vietnamese", code: "VI", status: "Synced", done: true },
        { lang: "Indonesian", code: "ID", status: "Synced", done: true },
        { lang: "Malay", code: "MS", status: "Synced", done: true },
        {
          lang: "Filipino",
          code: "TL",
          status: "Syncing…",
          done: false,
          active: true,
        },
      ],
      footer: "11 languages total — all automated",
    },
  },
  {
    number: "III",
    title: "All three modules run automatically",
    description:
      "Go live the moment setup is complete. Real-time chat responds 24/7, nightly batch processing analyzes all data automatically, and the proactive outreach engine sends personalized notifications on schedule. Zero manual intervention required.",
    visual: {
      type: "modules",
      title: "Module Status",
      items: [
        {
          label: "Real-time Chat Engine",
          sub: "340 concurrent sessions",
          status: "Running",
        },
        {
          label: "Nightly Batch Processor",
          sub: "Completed today at 02:30",
          status: "Done",
        },
        {
          label: "Proactive Outreach",
          sub: "102K notifications sent",
          status: "Running",
        },
        {
          label: "Multilingual Knowledge",
          sub: "11 languages · Up to date",
          status: "Synced",
        },
      ],
      footer: "Fully automated — no manual intervention needed",
    },
  },
];

function ChecklistVisual({ visual }: { visual: (typeof steps)[0]["visual"] }) {
  return (
    <div className="bg-background text-foreground overflow-hidden border border-background/10">
      <div className="px-6 py-4 border-b border-foreground/8 flex items-center justify-between">
        <span className="text-sm font-mono text-foreground/50">
          {visual.title}
        </span>
        <span className="text-xs font-mono text-foreground/40">
          Setup Wizard
        </span>
      </div>
      <div className="divide-y divide-foreground/6">
        {visual.items.map((item, i) => (
          <div
            key={i}
            className={`px-6 py-3.5 flex items-center gap-4 transition-colors ${"active" in item && item.active ? "bg-foreground/3" : ""}`}
          >
            <span
              className={`shrink-0 w-5 h-5 rounded-full border flex items-center justify-center transition-all ${item.done ? "bg-foreground border-foreground" : "active" in item && item.active ? "border-foreground/60" : "border-foreground/20"}`}
            >
              {item.done && <Check className="w-3 h-3 text-background" />}
              {"active" in item && item.active && !item.done && (
                <span className="w-1.5 h-1.5 rounded-full bg-foreground/60 animate-pulse" />
              )}
            </span>
            <span
              className={`text-sm transition-colors ${item.done ? "text-foreground/35 line-through" : "active" in item && item.active ? "text-foreground font-medium" : "text-foreground/40"}`}
            >
              {item.label}
            </span>
          </div>
        ))}
      </div>
      <div className="px-6 py-4 border-t border-foreground/8">
        <span className="text-xs font-mono text-foreground/45">
          {visual.footer}
        </span>
      </div>
    </div>
  );
}

function LanguagesVisual({ visual }: { visual: (typeof steps)[0]["visual"] }) {
  return (
    <div className="bg-background text-foreground overflow-hidden border border-background/10">
      <div className="px-6 py-4 border-b border-foreground/8 flex items-center justify-between">
        <span className="text-sm font-mono text-foreground/50">
          {visual.title}
        </span>
        <span className="flex items-center gap-2 text-xs font-mono text-green-600">
          <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
          Syncing
        </span>
      </div>
      <div className="divide-y divide-foreground/6">
        {visual.items.map((item, i) => (
          <div
            key={i}
            className={`px-6 py-3.5 flex items-center justify-between transition-colors ${"active" in item && item.active ? "bg-foreground/3" : ""}`}
          >
            <div className="flex items-center gap-3">
              <span className="font-mono text-xs text-foreground/40 w-6">
                {item.code}
              </span>
              <span
                className={`text-sm ${item.done ? "text-foreground/70" : "active" in item && item.active ? "text-foreground font-medium" : "text-foreground/35"}`}
              >
                {item.lang}
              </span>
            </div>
            <span
              className={`text-xs font-mono px-2 py-0.5 rounded-sm ${item.done ? "text-green-700 bg-green-500/12" : "active" in item && item.active ? "text-foreground/70 bg-foreground/6" : "text-foreground/25"}`}
            >
              {item.status}
            </span>
          </div>
        ))}
      </div>
      <div className="px-6 py-4 border-t border-foreground/8">
        <span className="text-xs font-mono text-foreground/45">
          {visual.footer}
        </span>
      </div>
    </div>
  );
}

function ModulesVisual({ visual }: { visual: (typeof steps)[0]["visual"] }) {
  const statusColor: Record<string, string> = {
    Running: "text-green-700 bg-green-500/12",
    Done: "text-foreground/50 bg-foreground/6",
    Synced: "text-green-700 bg-green-500/12",
  };

  return (
    <div className="bg-background text-foreground overflow-hidden border border-background/10">
      <div className="px-6 py-4 border-b border-foreground/8 flex items-center justify-between">
        <span className="text-sm font-mono text-foreground/50">
          {visual.title}
        </span>
        <span className="flex items-center gap-2 text-xs font-mono text-green-600">
          <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
          All online
        </span>
      </div>
      <div className="divide-y divide-foreground/6">
        {visual.items.map((item, i) => (
          <div key={i} className="px-6 py-4 flex items-center justify-between">
            <div>
              <div className="text-sm font-medium text-foreground mb-0.5">
                {item.label}
              </div>
              <div className="text-xs font-mono text-foreground/50">
                {item.sub}
              </div>
            </div>
            <span
              className={`text-xs font-mono px-2.5 py-1 rounded-sm ${statusColor[item.status] ?? "text-foreground/40"}`}
            >
              {item.status}
            </span>
          </div>
        ))}
      </div>
      <div className="px-6 py-4 border-t border-foreground/8 flex items-center gap-3">
        <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
        <span className="text-xs font-mono text-foreground/50">
          {visual.footer}
        </span>
      </div>
    </div>
  );
}

function StepVisual({ visual }: { visual: (typeof steps)[0]["visual"] }) {
  if (visual.type === "checklist") return <ChecklistVisual visual={visual} />;
  if (visual.type === "languages") return <LanguagesVisual visual={visual} />;
  if (visual.type === "modules") return <ModulesVisual visual={visual} />;
  return null;
}

export function HowItWorksSection() {
  const [activeStep, setActiveStep] = useState(0);
  const [isVisible, setIsVisible] = useState(false);
  const sectionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) setIsVisible(true);
      },
      { threshold: 0.1 },
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveStep((prev) => (prev + 1) % steps.length);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  return (
    <section
      id="how-it-works"
      ref={sectionRef}
      className="relative py-24 lg:py-32 bg-foreground text-background overflow-hidden"
    >
      <div className="absolute inset-0 opacity-[0.03] pointer-events-none">
        <div
          className="absolute inset-0"
          style={{
            backgroundImage: `repeating-linear-gradient(-45deg, transparent, transparent 40px, currentColor 40px, currentColor 41px)`,
          }}
        />
      </div>

      <div className="relative z-10 max-w-[1400px] mx-auto px-6 lg:px-12">
        <div className="mb-16 lg:mb-24">
          <span className="inline-flex items-center gap-3 text-sm font-mono text-background/70 mb-6">
            <span className="w-8 h-px bg-background/50" />
            Onboarding
          </span>
          <h2
            className={`text-4xl lg:text-6xl font-display tracking-tight transition-all duration-700 ${isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"}`}
          >
            Three steps to go live.
            <br />
            <span className="text-background/65">As fast as same day.</span>
          </h2>
        </div>

        <div className="grid lg:grid-cols-2 gap-16 lg:gap-24">
          <div className="space-y-0">
            {steps.map((step, index) => (
              <button
                key={step.number}
                type="button"
                onClick={() => setActiveStep(index)}
                className={`w-full text-left py-8 border-b border-background/10 transition-all duration-500 group ${activeStep === index ? "opacity-100" : "opacity-40 hover:opacity-70"}`}
              >
                <div className="flex items-start gap-6">
                  <span className="font-display text-3xl text-background/30">
                    {step.number}
                  </span>
                  <div className="flex-1">
                    <h3 className="text-2xl lg:text-3xl font-display mb-3 group-hover:translate-x-2 transition-transform duration-300">
                      {step.title}
                    </h3>
                    <p className="text-background/75 leading-relaxed">
                      {step.description}
                    </p>
                    {activeStep === index && (
                      <div className="mt-4 h-px bg-background/20 overflow-hidden">
                        <div
                          className="h-full bg-background w-0"
                          style={{ animation: "progress 5s linear forwards" }}
                        />
                      </div>
                    )}
                  </div>
                </div>
              </button>
            ))}
          </div>

          <div className="lg:sticky lg:top-32 self-start">
            <div
              key={activeStep}
              style={{
                animation:
                  "fadeSlideIn 0.4s cubic-bezier(0.22, 1, 0.36, 1) forwards",
              }}
            >
              <StepVisual visual={steps[activeStep].visual} />
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        @keyframes progress {
          from {
            width: 0%;
          }
          to {
            width: 100%;
          }
        }
        @keyframes fadeSlideIn {
          from {
            opacity: 0;
            transform: translateY(12px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
      `}</style>
    </section>
  );
}

// components/landing/how-it-works-section.vue
<template>
  <section id="how-it-works" ref="sectionRef" class="section">
    <!-- Diagonal lines pattern -->
    <div class="bg-pattern" />

    <div class="container">
      <!-- Header -->
      <div class="header">
        <span class="label">
          <span class="label-line" />
          Process
        </span>
        <h2 class="title" :class="isVisible ? 'visible' : 'hidden-up'">
          Three steps.
          <br />
          <span class="title-muted">Infinite possibilities.</span>
        </h2>
      </div>

      <!-- Main content -->
      <div class="content-grid">
        <!-- Steps -->
        <div class="steps">
          <button
            v-for="(step, index) in steps"
            :key="step.number"
            type="button"
            class="step-btn"
            :class="activeStep === index ? 'step-active' : 'step-inactive'"
            @click="activeStep = index"
          >
            <div class="step-inner">
              <span class="step-number">{{ step.number }}</span>
              <div class="step-body">
                <h3 class="step-title">{{ step.title }}</h3>
                <p class="step-desc">{{ step.description }}</p>
                <div v-if="activeStep === index" class="progress-track">
                  <div class="progress-bar" :key="activeStep" />
                </div>
              </div>
            </div>
          </button>
        </div>

        <!-- Code display -->
        <div class="code-panel">
          <div class="code-window">
            <!-- Window header -->
            <div class="window-header">
              <div class="window-dots">
                <div class="dot" />
                <div class="dot" />
                <div class="dot" />
              </div>
              <span class="window-filename">workflow.js</span>
            </div>

            <!-- Code content -->
            <div class="code-body">
              <pre class="code-pre">
                <div
                  v-for="(line, lineIndex) in steps[activeStep].code.split('\n')"
                  :key="`${activeStep}-${lineIndex}`"
                  class="code-line"
                  :style="{ animationDelay: `${lineIndex * 80}ms` }"
                >
                  <span class="line-num">{{ lineIndex + 1 }}</span>
                  <span class="line-chars">
                    <span
                      v-for="(char, charIndex) in line.split('')"
                      :key="`${activeStep}-${lineIndex}-${charIndex}`"
                      class="code-char"
                      :style="{ animationDelay: `${lineIndex * 80 + charIndex * 15}ms` }"
                    >{{ char === ' ' ? '\u00A0' : char }}</span>
                  </span>
                </div>
              </pre>
            </div>

            <!-- Status -->
            <div class="window-footer">
              <span class="status-dot" />
              <span class="status-text">Ready</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { ref, onMounted, onUnmounted } from 'vue'

const steps = [
  {
    number: 'I',
    title: 'Connect your tools',
    description: 'Integrate with your existing stack in minutes. We support 200+ data sources out of the box.',
    code: `import { optimus } from '@optimus/core'

optimus.connect({
  source: 'your-database',
  sync: true
})`,
  },
  {
    number: 'II',
    title: 'Build your workflow',
    description: 'Design powerful automations with our visual builder or write code directly.',
    code: `optimus.workflow('process', {
  trigger: 'event',
  actions: [
    'validate',
    'transform',
    'deliver'
  ]
})`,
  },
  {
    number: 'III',
    title: 'Ship to production',
    description: 'Deploy globally with zero configuration. Your app goes live in under 30 seconds.',
    code: `optimus.deploy({
  target: 'production',
  regions: 'auto'
})

// Deployed to 12 regions`,
  },
]

export default {
  setup() {
    const activeStep = ref(0)
    const isVisible = ref(false)
    const sectionRef = ref(null)
    let observer = null
    let interval = null

    onMounted(() => {
      observer = new IntersectionObserver(
        ([entry]) => {
          if (entry.isIntersecting) isVisible.value = true
        },
        { threshold: 0.1 }
      )
      if (sectionRef.value) observer.observe(sectionRef.value)

      interval = setInterval(() => {
        activeStep.value = (activeStep.value + 1) % steps.length
      }, 5000)
    })

    onUnmounted(() => {
      observer?.disconnect()
      clearInterval(interval)
    })

    return { steps, activeStep, isVisible, sectionRef }
  }
}
</script>

<style scoped>
.section {
  position: relative;
  padding: 96px 0;
  background: #111;
  color: #fff;
  overflow: hidden;
}

.bg-pattern {
  position: absolute;
  inset: 0;
  opacity: 0.03;
  pointer-events: none;
  background-image: repeating-linear-gradient(
    -45deg,
    transparent,
    transparent 40px,
    currentColor 40px,
    currentColor 41px
  );
}

.container {
  position: relative;
  z-index: 10;
  max-width: 1400px;
  margin: 0 auto;
  padding: 0 24px;
}

/* Header */
.header {
  margin-bottom: 64px;
}

.label {
  display: inline-flex;
  align-items: center;
  gap: 12px;
  font-size: 14px;
  font-family: monospace;
  color: rgba(255,255,255,0.5);
  margin-bottom: 24px;
}

.label-line {
  display: inline-block;
  width: 32px;
  height: 1px;
  background: rgba(255,255,255,0.3);
}

.title {
  font-size: clamp(2rem, 5vw, 3.75rem);
  font-weight: 700;
  letter-spacing: -0.02em;
  transition: opacity 0.7s, transform 0.7s;
}

.title.visible {
  opacity: 1;
  transform: translateY(0);
}

.title.hidden-up {
  opacity: 0;
  transform: translateY(16px);
}

.title-muted {
  color: rgba(255,255,255,0.5);
}

/* Grid */
.content-grid {
  display: grid;
  gap: 64px;
}

@media (min-width: 1024px) {
  .content-grid {
    grid-template-columns: 1fr 1fr;
    gap: 96px;
  }
  .header {
    margin-bottom: 96px;
  }
  .code-panel {
    position: sticky;
    top: 128px;
    align-self: start;
  }
}

/* Steps */
.step-btn {
  width: 100%;
  text-align: left;
  padding: 32px 0;
  border: none;
  border-bottom: 1px solid rgba(255,255,255,0.1);
  background: transparent;
  color: inherit;
  cursor: pointer;
  transition: opacity 0.5s;
}

.step-active { opacity: 1; }
.step-inactive { opacity: 0.4; }
.step-inactive:hover { opacity: 0.7; }

.step-inner {
  display: flex;
  align-items: flex-start;
  gap: 24px;
}

.step-number {
  font-size: 1.875rem;
  font-weight: 700;
  color: rgba(255,255,255,0.3);
  flex-shrink: 0;
  min-width: 40px;
}

.step-body { flex: 1; }

.step-title {
  font-size: clamp(1.25rem, 2.5vw, 1.875rem);
  font-weight: 700;
  margin: 0 0 12px;
  transition: transform 0.3s;
}

.step-btn:hover .step-title {
  transform: translateX(8px);
}

.step-desc {
  color: rgba(255,255,255,0.6);
  line-height: 1.7;
  margin: 0;
}

/* Progress bar */
.progress-track {
  margin-top: 16px;
  height: 1px;
  background: rgba(255,255,255,0.2);
  overflow: hidden;
}

.progress-bar {
  height: 100%;
  background: #fff;
  width: 0;
  animation: progress 5s linear forwards;
}

/* Code window */
.code-window {
  border: 1px solid rgba(255,255,255,0.1);
  overflow: hidden;
}

.window-header {
  padding: 16px 24px;
  border-bottom: 1px solid rgba(255,255,255,0.1);
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.window-dots {
  display: flex;
  gap: 8px;
}

.dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: rgba(255,255,255,0.2);
}

.window-filename {
  font-size: 12px;
  font-family: monospace;
  color: rgba(255,255,255,0.4);
}

.code-body {
  padding: 32px;
  font-family: monospace;
  font-size: 14px;
  min-height: 280px;
}

.code-pre {
  color: rgba(255,255,255,0.7);
  margin: 0;
}

.code-line {
  display: block;
  line-height: 2;
  opacity: 0;
  transform: translateX(-8px);
  animation: lineReveal 0.4s cubic-bezier(0.22, 1, 0.36, 1) forwards;
}

.line-num {
  color: rgba(255,255,255,0.2);
  user-select: none;
  display: inline-block;
  width: 32px;
}

.code-char {
  opacity: 0;
  filter: blur(8px);
  animation: charReveal 0.3s cubic-bezier(0.22, 1, 0.36, 1) forwards;
}

.window-footer {
  padding: 16px 24px;
  border-top: 1px solid rgba(255,255,255,0.1);
  display: flex;
  align-items: center;
  gap: 12px;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #4ade80;
  animation: pulse 1.5s ease-in-out infinite;
}

.status-text {
  font-size: 12px;
  font-family: monospace;
  color: rgba(255,255,255,0.4);
}

/* Animations */
@keyframes progress {
  from { width: 0%; }
  to { width: 100%; }
}

@keyframes lineReveal {
  to { opacity: 1; transform: translateX(0); }
}

@keyframes charReveal {
  to { opacity: 1; filter: blur(0); }
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.4; }
}
</style>
